workloads:
  a:
    runtime: podman
    agent: a
    runtimeConfig: '-p 8080:80'
    resources:
      cpu: 0.1
      memory: 64
  b:
    runtime: podman
    agent: b
    runtimeConfig: '-p 8080:80'
    resources:
      cpu: 0.1
      memory: 64
