apiVersion: v0.1
workloads:
  redis:
    runtime: podman
    agent: agent_A
    dependencies:
    runtimeConfig: |
      image: redis:7
  backend:
    runtime: podman
    agent: agent_B
    dependencies:
    runtimeConfig: |
      image: alpine:latest
  my_nginx:
    runtime: podman
    agent: agent_A
    dependencies:
      redis: ADD_COND_FAILED
    runtimeConfig: |
      image: ghcr.io/eclipse/kuksa.val/databroker:0.4.1
