apiVersion: v0.1
workloads:
  nginx:
    runtime: podman
    agent: agent_A
    dependencies: {}
    runtimeConfig: 'image: ghcr.io/eclipse/kuksa.val/databroker:0.4.1

      commandArgs: ["--insecure"]

      commandOptions: ["--net=host"]'
